#!/bin/bash
set -e

cd ..
(

out='docs/source/modules/builtins.rst'

cat 'docs/builtins_prefix.rst' > $out

cat >> $out <<- EOF

..
  This file is generated by generate_builtins.sh

EOF


function generate() {
    # generate a list of commands

    local cmd="$1"
    echo -e "\n$cmd\n=============================\n" >> $out

    python3 src/examples/shell_example.py help "$cmd" >> $out
    echo -e "\n" >> $out
}


# clear file
#echo > out
#echo -e 'Built-in commands' >> $out
#echo -e '#################' >> $out
#echo -e '\n..\n  This file is generated by generate_builtins.sh\n' >> $out


# TODO generate list of functions builtins
# python3 src/examples/shell_example.py builtins


# read file into array
IFS=$'\n'
sorted=()
while IFS= read -r line; do
    sorted+=("$line")
done < <(sort docs/builtins.txt)

# iterate array
echo "Generating docs for builtins..."
for cmd in "${sorted[@]}"; do
    echo " $cmd"
    generate "$cmd"
done

)
