#!/bin/bash
set -e

cd ..
(

out='docs/source/generated/builtins.txt'

#cat 'docs/builtins_prefix.rst' > $out

cat > $out <<- EOF

..
  This file is generated by generate_builtins.sh

EOF


function generate() {
    # generate a list of commands

    local cmd="$1"
    echo -e "\n$cmd\n=============================\n" >> $out

    python3 src/examples/shell_example.py help "$cmd" >> $out
    echo -e "\n" >> $out
}


# TODO generate list of functions builtins
# python3 src/examples/shell_example.py builtins

# read file into array
IFS=$'\n'
commands=()
while IFS= read -r line; do
    commands+=("$line")
done < <(sort docs/builtins.txt)

# iterate array
echo "Generating docs for builtins..."
i=1
for cmd in "${commands[@]}"; do
    # display current stage
    printf '\r%4s %s\t%-20s' "$i" "/${#commands[@]}" "$cmd"
    generate "$cmd"
    let i++
done

# clear line
echo

)
